title: <p align="center"> Prathamesh More </p>
logo: assets/img/me2.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/prathamesh-more-5259695a/">LinkedIn</a> |
  <a href="https://github.com/prathameshmore777">GitHub</a>

  <br>
  I'm working on DevOps, Aws-Cloud and Automations.
  I have total of 7 years of experience in which i have worked with Netcore Solutions, Atos, Oracle Finance.
  Currently working with Amdocs DVCI.
  <br>
  </p>



theme: jekyll-theme-minimal
